language: c

# use container infra for linux
dist: bionic
sudo: false

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y cmake python2.7 python2.7-dev python3.5 python3.5-dev python3.6 python3.6-dev gcc-5 g++-5 gcc-6 g++-6 gcc autoconf-archive bison build-essential ccache cmake curl flex git gperf joe libboost-all-dev libcap-dev libdouble-conversion-dev libevent-dev libgflags-dev libgoogle-glog-dev libpthread-stubs0-dev libkrb5-dev libpcre3-dev libnuma-dev libsasl2-dev libsnappy-dev libsqlite3-dev libssl-dev libtool netcat-openbsd pkg-config sudo unzip wget

os: osx

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env: TRAVIS_PYTHON=python2.7
    - os: linux
      env: CXX=g++-6 TRAVIS_PYTHON=python3.6
      compiler: gcc-6
    - os: linux
      env: CXX=g++-5 TRAVIS_PYTHON=python3.5
      compiler: gcc-5
    - os: linux
      env: CXX=g++-6 TRAVIS_PYTHON=python2.7
      compiler: gcc-6

before_script: ./travis/deps.sh

script: ./travis/run.sh

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 4r0YdH+438rubwFLFXiKw6qUTx1A0O2pX48NUqoTRG0idIGxJiL/JNqFca42pCJQcynf6o/9Syx8x3DDNGeGXgPxufXLb3O/0dQNjvUreINHLOgmcCdVdzKvGVDzVOQMtMYnNXCarH+0gSwAAinnANrFVuvQksRPJflzWLq3DPBU4YvyTNTgqnQkcVchwm2SXX2uYnJ5+MbQHWFLtjPj1f2it8iAciYjGyLBAuSn2MYpybbaNrVD9QkN+crR8aA22gBT0qpk7Wlb6yXZeGpPTk79oKF6MmWHNtw5qDbDflAElJzSX0tT3FN39BlLdHV/vHNDSrOo+fSVVtxGMK2rbfTFYzX9eIxKKvpxD76OlasQUZpaepORu4LNE5jQUKO7BEAd35yZ25F+075EhY7SIyse/Tzn0N5JmiOqUeAlkAqv0R01v7Mup/keOG+1/eU24Bj7pccBUJCmY7uOIQOI3/uzjDR1j6GBFBMf+GfscHNisSu6dUvtOd8OniwlzJUNFfCQajb/cmBOO1I/bzFTCPZkeguayQxWGH5TO1zcd6cioBQN1s/r52/HIenKcQpW26vKLD7C1lNK9OhyahGr9OAjsKkVvIentMuoD1WMEn/2X0zZWSwLqgWnU81/okAKKjbiyYvhX+DCYyO4I2EL8qz6oH/B91dMuqxODG75HHQ=
  file_glob: true
  file: archives/*
  on:
    repo: artem-zinnatullin/watchman
    tags: true
tags: true
